name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@latest
    - name: Build the Docker image
      run:
        echo "{{secrets.DOCKER_PASS}}" | docker login -u "shababather" --password-stdin
        docker image build -t shababather/welcome-app .
        docker push shababather/welcome-app
