name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "{{secrets.DOCKER_PASS}}" | docker login -u "shababather" --password-stdin
        docker build . --file Dockerfile --tag welcome-app:$(date +%s)
        docker push shababather/welcome-app:latest
